#!/bin/bash

# Converts Audio Media Library to another format
while getopts "tson" opt; do
  case $opt in
    t)
      target_directory=$OPTARG
      ;;
    s)
      source_directory=$OPTARG
      ;;
    o)
      old_format=$OPTARG
      ;;
    n)
      new_format=$OPTARG
      ;;
  esac
done

cp -rl "$source_directory" "$target_directory";



find $target_directory -type f -iname \*$old_format -print -execdir ffmpeg -i {} -loglevel error -q:a 6 -ar 44300 {}.$new_format & \; -execdir rm {} +; 
find $target_directory -type f -iname \*.$old_format.$new_format -execdir rename "s/$old_format.$new_format/$new_format/" {} +;
